theme: jekyll-theme-cayman
title: Yes Fam India
description: Find Yes Fam India groups, chats and events. We host events and connect you with yes fam members in your region.
github:
  is_project_page: false
